file1=open("Hw3.txt", "r")
for i in file1:
    print(i)
file2=open("Hw3.txt", "r")
print(file2.read())
file3=open("Hw3.txt", "r")
print(file3.read(5))
file4=open("Hw3.txt", "w")
file4.write("My name is Yingtong!\n")
file4.write("I have a dog called Charlie\n")
file4.write("My favourite food is Sushi\n")
file4.write("My favourite book is Shatter Me\n")
file4.close()
file5=open("Hw3.txt", "a")
file5.write("I have a 783 day streak on Duolingo!")